### PR TITLE
Add 'Bookmarks blacklist' setting

### PR DESCRIPTION
**Pull request by cjbassi**
Allows specifying bookmark folders whose contents should not be included in the bookmark vomnibar search

### CODE REVIEW

**Comment by gdh1995** [comment]
An interesting idea. Then do we need a "history blacklist" to filter out some history items?

**Comment by cjbassi** [comment]
That wouldn't be a bad idea either. It would be implemented slightly differently though since that would have to be some sort of pattern match.

**Comment by smblott-github** [comment]
This seems quite niche.  What's the use case?

**Comment by cjbassi** [comment]
Well blacklisting the porn folder for one, not gonna beat around the bush on that one :laughing:. But it's also good for blacklisting folders of random internet snippets/articles that can accumulate and get in the way of the standard websites people bookmark and frequently visit like youtube, reddit, etc.

**Comment by gdh1995** [comment]
Will it be needed to re-enable searching for those text, when a user type "/path/to/banned/folder" ?

**Comment by cjbassi** [comment]
@gdh1995 That's not a bad idea. If this is going to get merged then I could implement that if we want to. It's just that the logic would have to be changed a fair bit because that requires dynamic blacklisting during querying rather than during indexing of the bookmarks which is what is currently being done.

**Comment by smblott-github** [comment]
I still think this is pretty niche.  Let's just leave it for the moment and see whether anybody comes up with a compelling use case.

**Comment by cjbassi** [comment]
@smblott-github The main use case for this is more than likely going to be for nsfw folders, which I think is a compelling enough use case on its own imo.

**Comment by philc** [comment]
Closing as too niche to be in the main Vimium distribution, IMO. Thanks for prototyping the idea!

**Pull request closed without merging**
