### PR TITLE
Updated logo to current chromium.

### PR DESCRIPTION
**Pull request by brianvanburken**
Most project are not keen on updating a logo, but I'm still going to try it here ;). I noticed the current logo uses a chromium logo that dates back before 2011. I've changed it to the current logo to give it a up-to-date look.

Let me know what you think and if you have any feedback :). Also here is the PSD file for anyone who is interested: [vimium.psd.zip](https://github.com/philc/vimium/files/67916/vimium.psd.zip)

### CODE REVIEW

**Comment by smblott-github** [comment]
@philc?

**Comment by philc** [comment]
Great work; thank you @brianvanburken for the thoughtful change.

**Comment by brianvanburken** [comment]
Great to see that I can contribute to a project I love and use everyday! :smile:

**Comment by smblott-github** [comment]
@brianvanburken ... You seem to have an interest in the visual side of things.

Any ideas for how to improve this icon (without confusing existing users)?

snapshot

This shows as the page icon when the user has exclusion keys defined for the current page.

**Comment by brianvanburken** [comment]
@smblott-github I will take a look at it and make a PR if I've found a solution

**Pull request merged**
