### PR TITLE
Consider the alt-key status when trying to detect <c-[>

### PR DESCRIPTION
**Pull request by colin-kiegel**
see https://github.com/philc/vimium/issues/986#issuecomment-53955175

### CODE REVIEW

**Comment by smblott-github** [comment]
Thanks, @colin-kiegel.

**Comment by colin-kiegel** [comment]
Thank you so much - I had to disable vimium on a lot of pages due to this! I am looking forward to re-enabling it. :-)

**Comment by smblott-github** [comment]
As a temporary measure (and if you trust me), you could use [this](https://drive.google.com/file/d/0B-PWDBroAYxrNFJQaHFBbDVuMkU/view?usp=sharing) version of Vimium.  It already has this fix.  Drag and drop onto the extensions page.  You might have to enable developer mode.  And don't forget to disable the Chrome Store version.

(It won't pick up your existing Vimium configuration.)

**Comment by krokofant** [comment]
@smblott-github Any idea when this will be pushed out as stable? I didn't see any consistency about release schedule so I thought I'd ask :)

**Comment by colin-kiegel** [comment]
works now with vimium 1.57, finally I can type it again [[[[ :+1: 

Thank you! :-)

**Comment by noelpuru** [comment]
Im using version 1.59 and cannot map <c-[>. Is this a regression bug?

**Comment by smblott-github** [comment]
This is probably a very old bug, I think. `<c-[>` is hardwired as `Escape`, the check for `Escape` is done before the check for other mappings.

**Pull request merged**
