### PR TITLE
Adds important to hint marker font-family declaration

### PR DESCRIPTION
**Pull request by sco-tt**
Addresses #2163

### CODE REVIEW

**Comment by smblott-github** [comment]
Thanks, @sco-tt.

I can't reproduce this myself (possibly it's geo-dependent), however I'll take your and @philc's word for it.

**Comment by smblott-github** [comment]
@sco-tt.  I'm no expert on CSS.  However, I've been wondering whether this is the correct fix.  Somehow, Facebook's style is leaking into Vimium's style.  The fix here looks like patch.  Is there a better way to prevent the styles leaking in, e.g. using `vimiumReset`?

**Comment by sco-tt** [comment]
It might not be necessary to merge these changes; it looks like FB has updated the rule to 
`#facebook ._-kb span {
    font-family: inherit;
}`

and the rule without !important is sufficiently specific; I'm not longer seeing the issue on 1.56. I've checked on Chromium Canary Channel on OSX - and Chrome stable on Win 10. @philc are you seeing this? Perhaps it had already been pushed to @smblott-github 's part of the world when I made this PR.

**Comment by smblott-github** [comment]
Thanks for the update, @sco-tt.  I'll take the commit out again.

**Pull request merged**
