### PR TITLE
Add commands for fullscreening, maximising, minimising and restoring a window

### LINKED ISSUE #1206: [feature request] full screen shortcut
Is it possible to add a shortcut to toggle fullscreen? f11 is too far up.

### PR DESCRIPTION
**Pull request by mrmr1993**
Resolves #1206.

### CODE REVIEW

**Comment by joshuacox** [comment]
merge this in, this is definite;y needed

**Comment by smblott-github** [comment]
From #1206...

> `F11` is too far up.

That's not a very strong case.

Would this stuff not be better handled by a window manager?

**Comment by mrmr1993** [comment]
> Would this stuff not be better handled by a window manager?

Arguably yes, expect for fullscreening. I think we should be looking for ways to support and document more commands, rather than reasons to bin them. Just my €0.02.

**Comment by smblott-github** [comment]
> expect for fullscreening

Yes, and we have `F11` for that.
Closing this.

(There's clearly a discussion needed around how to support more commands, present them to the user, and yet maintain a coherent set of commands.)

**Pull request closed without merging**
