### PR TITLE
Implement moveTabToNextWindow

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

## Description

#2407

### CODE REVIEW

**Comment by nikinbaidar** [comment]
> Signed-off-by: Gábor Lipták [gliptak@gmail.com](mailto:gliptak@gmail.com)
> ## Description
> 
> #2407

Tested this PR and works well. But Is there a way that
* the tab that has been just moved gets the focus in the next window
* If a new window is not open then spwan a new window and move this tab there

**Comment by gliptak** [comment]
@nikinbaidar thank you for reviewing. first one seems to be a design decision. as for the second one, you ca use the existing `W` (`moveTabToNewWindow`) command

@philc please review

**Comment by nikinbaidar** [comment]
How did I miss `moveTabToNewWindow`.. Although I have to press <F6> to focus the browser window before I continue using any kind of keyboard shortcuts.

**Comment by gliptak** [comment]
#3962

**Pull request closed without merging**
