### PR TITLE
Queue UIComponent requests until the frame has loaded

### LINKED ISSUE #1679: Another race condition vis-a-vis the HUD
If you enter insert mode immediately as the page loads, you can get a visible but empty HUD.

This seems to be happening because the HUD iframe (and port) have not yet initialised, so we're not sending the HUD contents to the iframe.

### PR DESCRIPTION
**Pull request by mrmr1993**
This fixes #1679.

### CODE REVIEW

**Comment by smblott-github** [comment]
@mrmr1993.  I had been thinking about using an `AsyncDataFetcher` [here](https://github.com/philc/vimium/blob/master/lib/utils.coffee#L296). to fix this.  Would that be an alternative?

**Comment by mrmr1993** [comment]
Yes, that would be. Equivalently, we could use [Promises](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) if we're willing to drop support for Chrome <32.

**Comment by smblott-github** [comment]
@mrmr1993.  I think #1685 is the way to go on this.  It avoids the need for yet another queue implementation.

**Comment by mrmr1993** [comment]
Okay, that's fine.

**Pull request closed without merging**
