### PR TITLE
Fix over-riding of vomnibar display CSS.

### LINKED ISSUE #1594: In v1.50, the vomnibar is always visible and won't close on certain sites
I am on Chrome Version 39.0.2171.71 (64-bit) on Arch Linux.
When I open this site: http://motorbeam.com/, the vomnibar is always visible and won't close or even work.

### PR DESCRIPTION
**Pull request by smblott-github**
@mrmr1993.  This seems to fix #1594.  I'm no CSS expert.  Is this safe?

Fixes #1594.

### CODE REVIEW

**Comment by mrmr1993** [comment]
This is fine as a quick fix, LGTM.

As I mentioned in #1594, we should consider using a shadow DOM to stop these problems altogether. Otherwise we're always in danger of inheriting some weird page style that is `important!`, and there's not a lot we can do about it.

**Comment by smblott-github** [comment]
> As I mentioned in #1594, we should consider using a shadow DOM...

Yes. (But I'm not confident doing that.)

**Comment by mrmr1993** [comment]
> But I'm not confident doing that.

I'll throw together a PR for you to have a look at shortly.

**Comment by smblott-github** [comment]
OK, thanks.  I'll merge this for now.

**Pull request merged**
