### PR TITLE
Separate the hud from frontend code and rewrite tween to be more generic

### PR DESCRIPTION
**Pull request by mrmr1993**
This is the first stage of another attempt at HUD-in-iframe, replacing #1474. This re-attempt will focus on
* having smaller, easier to review commits
* being spread across several PRs, so the whole feature doesn't go stale and need re-writing again
* working with modes properly, not as an after-thought (#1474 was a rebase of #1401, which pre-dated modes).

This PR
* moves the `HUD` class to its own file
* moves styles into the css file
* disentangles `Tween`, rewriting it to be generic enough to support a `UIComponent`.

The diff is large because of moving code; reviewing commit by commit is far easier.

@smblott-github can you take a look over this when you get a chance?

### CODE REVIEW

**Comment by smblott-github** [comment]
@mrmr1993.
Will do.

(And I appreciate your step-by-step approach.)

**Comment by smblott-github** [comment]
Just to add...

I remember from before that there was a problem having the focus in an iframe.  It means the focus is not on the page, which means that inputs never have the focus, which means that selections within inputs aren't actually selected, which means they're not visible.

**Comment by mrmr1993** [comment]
> I remember from before that there was a problem having the focus in an iframe.

I'm aware of that; in the next PR I plan to move the HUD into an iframe as is, so that the subsequent PR can be dedicated solely to accepting input in the HUD and the related focus issues. Hopefully this fragmented approach will make it easier to see what changes need to be made for that, make those changes, and keep the code current wrt master.

**Comment by smblott-github** [comment]
Good plan.

**Comment by smblott-github** [comment]
Thanks, @mrmr1993.  I guess you're good to go on the next stage of your plan.
Bit-sized pieces really helps!

**Comment by smblott-github** [comment]
@mrmr1993.  Could you take a look at 7004420e178416cc680416091a23dd804fb9370c, please?

**Comment by smblott-github** [comment]
@mrmr1993.  I was still seeing errors.  See 26f91fea40f11c116497ce20c1fe53f3956a922f too.

**Comment by mrmr1993** [comment]
@smblott-github good call on 26f91fe, I'd completely missed that.

I've pushed #1658 as a follow-up to this.

**Pull request merged**
