### PR TITLE
New feature/command: Mute/unmute tab.

### PR DESCRIPTION
**Pull request by tobimensch**
Mute/Unmute feature/command analogous to pin/unpin command.

### CODE REVIEW

**Comment by smblott-github** [comment]
Thanks, @tobimensch.

I believe I may have said "no" to this feature in the past.  However, it is frequently requested, and the implementation is very simple, so I'm minded to merge this.

Just let me think a bit.

See ffebb6dd15a9320842603854109149bc26078ae5.

**Comment by tobimensch** [comment]
@smblott-github:

Well, I'm hopeful you'll merge it. That fix you made in main.coffee line 213 I also had locally, but forgot to push it.

**Comment by smblott-github** [comment]
@tobimensch.  Here's my current thinking on this.

If we release `toggleMuteTab`, then users will immediately request `toggleMuteAllTabs`.

One of the problems we face with Vimium is keeping the feature set small, discoverable and manageable (both for maintainers, and so that it's not overwhelming for new users).  If we were to add every command which users request, then things would rapidly get out of hand.  So, my preference is to be pretty selective when adding new commands.  Read more [here](https://github.com/philc/vimium/blob/master/CONTRIBUTING.md#vimium-design-goals).

One way around this is to have simple, clear commands which are useful to a large number of users, but with more advanced features too, but which are described only in the wiki (for example, [here](https://github.com/philc/vimium/wiki/Tips-and-Tricks#keyboard-shortcuts-for-custom-search-engines) and [here](https://github.com/philc/vimium/wiki/Tips-and-Tricks#custom-key-mappings-with-a-count)).

In this case, I'm wondering whether we shouldn't add what you have here:

    map <a-m> toggleMuteTag

as is, but also add

    map <a-M> toggleMuteTag all

as an advanced feature (with no default binding, and described only on the wiki).

If we do the latter, then we would have to think carefully about what it means to mute all tabs.  Here's a proposal:

- If there is at least one tab which is `audible` ([here](https://developer.chrome.com/extensions/tabs#method-query)) and not muted, then mute all `audible` tabs.
- otherwise, unmute all muted tabs.

**Comment by tobimensch** [comment]
@smblott-github 
I like your proposal.

Especially toggleMuteTab other would be extremely useful.

**Comment by tobimensch** [comment]
I'd actually map
<a-M> to toggleMuteTag other

by default. Since toggleMuteTab all is essentially toggleMuteTag other + toggleMuteTag (this).

And leave toggleMuteTab all for the user to map himself.

**Comment by smblott-github** [comment]
OK.  I'm going to tweak this PR and merge it.  I'll take a look at the other features we've discussed (unless you'd prefer to, @tobimensch).

**Pull request merged**
