### PR TITLE
Re-introduce ctrl, shift keys as link hint mode modifiers

### LINKED ISSUE #1096: Opening link in new window behaviour
With the newest update of vimium  i was no longer able to open links in new tabs by,

press `f` -> (let say`PC` is one of the suggestions) press `pC`.

This used to work consistently till now. I have to now resort to `F -> pc`.

### PR DESCRIPTION
**Pull request by mrmr1993**
This fixes #1096.

### CODE REVIEW

**Comment by smblott-github** [comment]
From #1104, @z0rch asked...

> Is there anything, that blocks us from merging... ?

Issue:
- Why does this mention `@mode == OPEN_WITH_QUEUE`?

I can't find the commit which disabled the original functionality.  If you can find it, @z0rch, I'll take a look.  I'd like to make sure we're returning it to how it was.

**Comment by z0rch** [comment]
@mrmr1993 is the best person to collaborate on the change of `@mode == OPEN_WITH_QUEUE`.

@smblott-github, here's how I understand the chronology:

1. [63f0b24](https://github.com/philc/vimium/commit/63f0b24d35176e6f72429e6c4ed15b9282c6e21b) of #1036 broke the behavior on Linux on Apr 25, 2014.
2. Due to many complains, @mrmr1993 reverted that commit in [346c421](https://github.com/mrmr1993/vimium/commit/346c4212d771ee70dea098c2f1d0142af154f139) on Jul 28, 2014.
3. `@mode == OPEN_WITH_QUEUE` was introduced separately in [dc3360b](https://github.com/mrmr1993/vimium/commit/dc3360b6b0c0cde4e4e5fba4de19da12044c9344) on Aug 2, 2014.
4. I discovered this issue only in Dec 2014, when I got a Linux on my machine. Back then I didn't find the points above, but I investigated the difference between Linux and Windows behavior, and that resulted in #1292. I closed that PR as a duplicate after I found that @mrmr1993 already proposed #1104, which was already being actively discussed.

Since then I'm running a fork of philc/master with merged #1104, it seems to work fine for my regular workflow.

**Comment by smblott-github** [comment]
OK.  I merged.  Reworked slightly -- 9eedb3e2288dfaa401159740e32e14f682217ff4 -- perhaps someone could double check my logic.

**Comment by z0rch** [comment]
Looks reasonable to me. Thanks for merging! :balloon:  :cake:

**Pull request closed without merging**
