### PR TITLE
Use "keypress" for link hints (instead of "keydown")

### LINKED ISSUE #1387: Open links won't work with different language input method
I have multiple layouts: english and russian.  I can use almost all functionality of vimium extension with russian layout and mapping. But i can't choose links by letters from another layout (no mappings). 
Please bind shortcuts to actual physical keys or create mappings for letters

### PR DESCRIPTION
**Pull request by smblott-github**
Currently, if the user sets non-ASCII link-hint characters on the options page, they can't select links because we use the `keydown` event.  This uses `keypress` instead.  It should be the case that whatever characters the user can type into options-page option (from which we generate link hints), they can later type those same characters to activate link hints.

(Also, exit link-hints mode on `click` and `scroll` events.)

~~Fixes~~ Related to #1387 (I think).

### CODE REVIEW

**Comment by mrmr1993** [comment]
I have the same concerns about this that I did about the related change in #1716: a Russian user who also uses `en_US` (eg. with [this keyboard](http://ep.yimg.com/ay/yhst-16016120845095/russian-and-english-bilingual-black-keyboard-2.png)) could always select the correct link hints with the default settings by pressing the key that shows the character that's next in the link hint.

After this change, they will have to choose a locale for link hints, and switch keyboard layout to it every time they want to click a link. This is arguably worse than what #1716 did for such a user, since they have no way of mitigating it.

@smblott-github can we have an option allowing users to return to the old behaviour?

**Comment by smblott-github** [comment]
I hear you, @mrmr1993.  And I agree that this case is different (the user has just one set of hint characters, so they have to be able to use them).

@vans239, @grey0ne.  You commented over in #1387.  Could you provide some input here?  The idea is that you can set and use non-Latin characters for link hints (e.g. Russian).  @mrmr1993's concern is that, by doing this, the Russian (say) characters wouldn't be available *at all* if the user changed locale.

**Comment by smblott-github** [comment]
(As implemented here, this is broken.  It doesn't handle `Delete` correctly.)

**Comment by mrmr1993** [comment]
> It doesn't handle `Delete` correctly.

Nor the `shift`/`ctrl` modifiers.

**Comment by smblott-github** [comment]
@mrmr1993.  Is the following correct?

###### If we stick with `keydown`, then...

- **A** - A Russian user who sets their alphabet hint keys to `фывапролд` cannot ever use alphabetical hints.
- **B** - Filtered hints can never be used on websites which use non-ASCII characters.

Both of these are very serious.

###### If we move to `keypress`, then ...

- **C** - A user with non-ASCII alphabet hint keys may have to change their locale to use alphabetical hints.
- **D** - Similarly, a user may have to change their locale (to match that of the website) to use filtered hints.

###### So...

If the above is correct, the **A** and **B** are really bad, **C** and **D** aren't great, but they're not show stoppers.

**Comment by mrmr1993** [comment]
That's right.

There's also the case where the user is on a page with one locale but their filter hints characters use another; there the user has to choose before they start (since they probably can't switch given how readily we exit link hint mode).

All in all, I'll conceed that `keypress` is probably the way to go for now, but it would be good to have an option to fall back to/only use `en_US` (via `keydown`). #1676 would be a nice place to start with this, if that's something we would consider doing.

**Comment by smblott-github** [comment]
@mrmr1993....

See 6b29f4bb9fec6c61054c2037289d7ca6c0249c10 (currently on a different branch).  For alphabet hints, we can preserve the existing behaviour for existing users who are used to it, and support non-Latin characters too.  Might that be too confusing for users?

Doing the same thing for number hints isn't quite so obvious (since we match against both the hint characters and the hint texts).  We *could* look for non-ASCII characters in all of the hint texts, and choose `keydownKeyChar` if there are none.  However, then a single non-ASCII character (e.g. `é`) in the hint texts would change the behaviour.  Which seems too confusing for users.

**Comment by mrmr1993** [comment]
@smblott-github that looks great, it should cover the cases I was concerned about nicely. (NB: The `useKeydown` regexp could include `0-9` as well without causing any problems.)

> Doing the same thing for number hints isn't quite so obvious... seems too confusing for users.

Agreed. Being able to filter links with non-ASCII characters is a big positive here, so it seems fair to let that and simplicity take priority.

**Comment by smblott-github** [comment]
@mrmr1993.  This is merged now.  Could you watch out for gotchas vis-a-vis alphabet hints, please?  I use filter hints.

**Comment by mrmr1993** [comment]
@smblott-github I missed it when this was merged, but this breaks the `<ctrl>` modifier for link hints, since chrome shortcuts are fired for e.g. `<c-a>`, `<c-s>`, etc.

(Clearly nobody uses that modifier in link hints mode, but still something worth considering.)

**Pull request merged**
