### PR TITLE
Key mappings for Shift + [non-printable char key]

### PR DESCRIPTION
**Pull request by alexei-zayakin**
Currently it is impossible to create a key mapping for combinations like `Shift + Left` or `Shift + F1`.

Proposed changes make it possible using `<s-left>` syntax.

### CODE REVIEW

**Comment by gdh1995** [comment]
I agree that `<Shift+Fn>` should be supported, but I think `<f1> / <F1>` and `<left> / <LEFT>` are better than a new modifier `s`.

**Comment by alexei-zayakin** [comment]
Currently, `<left> / <f1>` are case insensitive, thus I thought a new modifier would be better than changing behavior for some existing combinations.

Anyways, I am completely okay with any implementation, just want to use that feature.

**Comment by smblott-github** [comment]
@gdh1995... I prefer this to #2390.  Suggest we do this a close the other one.

**Comment by gdh1995** [comment]
Well, this indeed seems a good solution.

My PR is from my project [Vimium++](https://github.com/gdh1995/vimium-plus), and it has supported keys like `<LEFT>` for years. @smblott-github, since users of Vimium are so much more than those of mine extension, what Vimium chooses is up to you. I'll change Vimium++ to make it support `<s-*>` too.

**Comment by sluongng** [comment]
could we pls have this?

**Comment by gdh1995** [comment]
Now I've given my idea of "<LEFT>" and  turned to this PR of "<s-left>".

**Comment by philc** [comment]
@gdh1995 @alexei-zayakin I'll merge this if it can be updated to merge cleanly (the code has changed since original authoring). Ideally we also have a test case for this in commands_test.coffee.

**Comment by gdh1995** [comment]
Oh this is safe to merge.

The conflicting line is `keyChar = keyChar.toUpperCase() if event.shiftKey and keyChar.length == 1`, which "has been added" into the master branch.

**Comment by philc** [comment]
Merged in ebc57ba7b8c45a0ccfb6710a6989cce73ac19f11. Nice. Thanks!

**Comment by politicus** [comment]
What a great news! More mappings available!

Can we get a list of the keys that now can be mapped the following way <s-NameOfTheKey>?

I tried and successfully mapped the four arrow keys: 
map <s-left> LinkHints.activateMode action=copy-text
map <s-down> LinkHints.activateMode action=hover
map <s-up> LinkHints.activateMode action=focus
map <s-right> LinkHints.activateMode

**Pull request closed without merging**
