### PR TITLE
Implemented closeWindow command with default binding :q

### LINKED ISSUE #1872: Add a binding to quit the browser
I'd like to be able to bind a key to quit the browser completely. Equivalent to Alt-F4, Ctrl-Shift-Q, or closing the window.

### PR DESCRIPTION
**Pull request by Reilithion**
Fixes #1872. This turned out to be easy.

### CODE REVIEW

**Comment by smblott-github** [comment]
Thanks, @Reilithion.

I still think, though, that this is a window-manager issue.

**Comment by Reilithion** [comment]
Maybe it is. But a good user interface provides redundancy for important operations, and I don't want to always rely on my window manager to be able to exit Chromium.

This feature meets at least 5/6 if not 6/6 of the standards for Good features listed it CONTRIBUTING.md. The only one that's remotely questionable is 1: Useful for lots of Vimium users. Including it has practically no cost - it's less than 10 lines of code. If you're concerned someone might accidentally hit ":q" and get confused or frustrated with Vimium, we can go in and remove the default binding, requiring a user to configure this feature before it can be used and preventing such a scenario.

Moreover, I want this feature. I installed Vimium in the first place in part because I presumed Vimium would provide it. Please accept this Pull request or ask me to improve it. I see no practical reason not to.

**Comment by mrmr1993** [comment]
@Reilithion see #1269 (and the issues referencing it linked there) for some related discussion.

**Comment by smblott-github** [comment]
Closing.
Window manager issue. And `999x` works well enough in Vimium, if you really want this capability.

(Thanks, though, @Reilithion.)

**Pull request closed without merging**
