### PR TITLE
Fix grab back focus after web navigation

### LINKED ISSUE #1588: Search text box on github "stealing" focus after "follow next link"
This is a similar issue to the one I opened for [cVim here](https://github.com/1995eaton/chromium-vim/issues/276).

### PR DESCRIPTION
**Pull request by smblott-github**
@mrmr1993:  I included `form_submit` (in addition to `link`) in the list.  What do you think?

Fixes #1588.

### CODE REVIEW

**Comment by mrmr1993** [comment]
Code LGTM, I'll try and test it when I have some time later.

**Comment by smblott-github** [comment]
Merging.
Seems to work well, and if there are any issues or gotchas it's not hard to unwind.

**Comment by smblott-github** [comment]
> ... and if there are any issues or gotchas it's not hard to unwind.

And there are gotchas.

This breaks search on Google Inbox.  `/` invokes a navigation, so the search box loses the focus.  The UX resolving things is ugly.

The lesson is that, when it comes to grabbing back the focus, we should tread lightly.

Reverted.

**Comment by mrmr1993** [comment]
Broken record, but: my suggestion in #1588 is more conservative, and will fix the issue. I'll open a PR for it at some point.

**Comment by smblott-github** [comment]
> I'll open a PR for it at some point.

Suggest you hold off.  You'll just run into the same types of issue.

(I'm wondering whether we should can this grab-back-focus lark entirely.)

**Comment by mrmr1993** [comment]
> You'll just run into the same types of issue.

Shouldn't do. I considered the types of breakage (including the one you ran into) when I was devising my solution. You can see me predicting this bug in #1588.

**Pull request merged**
