### PR TITLE
Add shortcut to pin/unpin Tab

### PR DESCRIPTION
**Pull request by fukayatsu**
- Press `.` to pin/unpin current tab

### CODE REVIEW

**Comment by clebrun** [comment]
Is there anyway to change this locally? Alt is captured by my window manager, so <a-p> doesn't work for me.

**Comment by smblott-github** [comment]
@clebrun I use `gp` for this.  On the options page, add `map gp togglePinTab` to your "Custom key
mappings".

**Comment by clebrun** [comment]
Thanks, it works great!

**Comment by Koleok** [comment]
@smblott-github score! 😄

**Pull request merged**
