### PR TITLE
Adds new check to see if an element is covered by another

### PR DESCRIPTION
**Pull request by poacher2k**
Replaces #2166

### CODE REVIEW

**Comment by smblott-github** [comment]
The right-hand *Suggested Groups* pane on Facebook....

Before...

snapshot

After...

snapshot

We're now missing a lot of hints.  Any ideas, @poacher2k?

**Comment by poacher2k** [comment]
Good find! It seems that the case with these missing links is that the wrapping anchor tag itself doesn't have a any box size, and therefore only its children are found with `document.getElementFromPoint`.
anchor tags:
image
direct children:
image

I'll have to do some thinking here, as this is in theory correct behavior (click candiate is not in fact a visible element), but in practice not quite so.

Let me know if you come up with any ideas as well!

**Comment by poacher2k** [comment]
@smblott-github I added a fix, and as far as I can see, things are working really smoothly now. Did some more extensive testing on facebook, reddit and github, and it seems to improve things a lot.

**Comment by smblott-github** [comment]
@poacher2k... See 5a32ecdd858cc95e504129747a5580dc27590b68.

I'm going to try it out for a bit before merging.

(Tests aren't passing for now.)

**Comment by poacher2k** [comment]
I'm also trying it out, but yeah - I see tests aren't passing. Any clue on why, or hints on how to debug the tests that are failing?

**Comment by smblott-github** [comment]
@poacher2k... I'm still using [this branch](https://github.com/smblott-github/vimium/tree/poacher2k-master-squashed) which includes your work tweaked and squashed.  Are you too?

Do you have any sense as to whether it's faster or slower than the status quo?

I good test is to scroll a looooong way down on Twitter or Google Plus and then activate hints.

**Comment by poacher2k** [comment]
@smblott-github: I'll do some tests on this after work today!

I believe the tweaked version (with only one check instead of two) is definitively faster than the one with two, but you might be talking about the main vimium branch?

**Comment by smblott-github** [comment]
> is definitively faster than the one with two

That's what I think.

**Comment by poacher2k** [comment]
Then I think we should go for that one. The reason I reverted the tweak was because Travis failed to build with the tweak and succeeded without it.

**Comment by smblott-github** [comment]
Tests are fixed over in my branch of this: 1c66503d1d2d1352ffacf0d9753d8310ea35aaf9.

The problem was that the tests were making too many assumptions about the implementation.

**Comment by poacher2k** [comment]
That's great! I feared I had broken something. Will be testing with your branch soon.

**Comment by poacher2k** [comment]
I tested on twitter.com scrolled down far enough to make document.body.scrollHeight ~157k, and did some timings from F was pressed until hints appeared.

On master: ~0.7s
On poacher2k-master-squashed: ~0.84s
On poacher2k-master-squashed with tweak: ~0.7s

Seems pretty solid to me, will do some more testing when I come back home.

**Comment by poacher2k** [comment]
Tried going as far down I could on Twitter, Reddit and Facebook - all sites with loads of elements - and it never really goes more than ~0.9s for the link hints to show.

It should be said that at the bottom of Reddit/Twitter, the entire browsing experience gets sluggish - not just vimium.

**Comment by smblott-github** [comment]
@poacher2k...  Thanks for that.

Now, a problem.  From Facebook....

snapshot

`master` finds the link labelled "44" (probably the most important link!).  Your approach (as implemented over in my other branch), *does not*.  This happens consistently (for all Guardian posts), but I cannot find other examples.

**Comment by poacher2k** [comment]
Hmm, I can't reproduce this it seems.

image

Do you experience it every time? Definitively worrisome, as that's the most important link for sure!

**Comment by poacher2k** [comment]
Is there any interest for me to work this into the current codebase? As far as I can see, this is still an issue that when solved could improve the user experience on several websites.

Some examples:
github
GitHub
reddit
Reddit
YouTube
YouTube
Medium
Medium (only 4 of these are actually clickable with the mouse)

**Comment by poacher2k** [comment]
Looking at the https://github.com/philc/vimium/pull/2251#issuecomment-249766333 I realise I actually _did_ reproduce it in https://github.com/philc/vimium/pull/2251#issuecomment-249983140 . 

Not really sure what is happening here (and the post is long gone), but I believe the "44" label may have been underneath the main post thumbnail and not actually visible although correctly placed. 

I'll take extra notice of this if/when doing more work on this.

**Comment by philc** [comment]
I looked at this and followed the comment history, but couldn't find a the original rationale, or recent examples. However, I did reproduce this modern example from medium. 1st is before this patch, 2nd is after. You can see that the 2nd screenshot omits many link hints which aren't clickable by the mouse because they're under an overlay, so they probably shouldn't be exposed by link hints (even though they are indeed clickable if the overlay is removed).

I've squashed this to one commit, tidied up some comments, and merged it into master in caf13c2dbfa9b3c5f35aae76dfcffa4cfea14bac. We can now easily test and revert this if it surfaces many suboptimal edge cases once it hits a wider audience.

I didn't want to lose this PR in the upcoming migration away from coffeescript.

CC @gdh1995 in case you've modified Vimium-C's linkhints in this way and have any commentary.

**Comment by gdh1995** [comment]
I haven't implemented this, maybe because of concerns about speed / code size. But this indeed looks well, and now I agree that it should be executed.

**Comment by poacher2k** [comment]
Wow @philc , this is certainly a pleasant surprise! Thank you so much for looking at this! I've been eagerly wanting this ever since I made the PR in 2016! :)

**Comment by gnarendran** [comment]
This seems to break  "Traverse shadow DOM to find links #3406" - particularly if the test on element.contains rejects shadow elements...

**Comment by philc** [comment]
Follow-up discussion about @gnarendran's comment is in #3474

**Comment by RomainBitard** [comment]
I believe this change makes me miss a lot of links that I could navigate before without the mouse, now I have to partially use the mouse some times (😞). 
Am I the only one with this issue now ?

**Comment by poacher2k** [comment]
@RomainBitard : would be great with some links and screenshots so that those issues can be ironed out in that case :)

**Comment by gnarendran** [comment]
@RomainBitard : You are not alone, there are already followup issues  #3492 #3493 #3501(closed). But I do not know if these three are the only regressions, and if you have encountered a different one. I guess that is why @poacher2k is requesting your problem links. Regards.

**Pull request closed without merging**
