### PR TITLE
Direct keyboard access to custom-search engines via keyword flag

### PR DESCRIPTION
**Pull request by smblott-github**
This extends the `map` command for *Custom key mappings* such that mappings (only for `vomnibar.activate`, here) can optionally take extra flags.  This idea was first mooted in #1269.

Here, the extra flag is a custom search-engine keyword.  Something like:

    map s vomnibar.activate keyword=g

Assuming a custom search engine...

    g: http://www.google.com/search?q=%s Google

the user can then launch Google search (with completion) with a single keystroke. So, with this example, the user types `s` and immediately gets...

snapshot

This is an alternative to #1695 (a better alternative, I think, since 1) it does not require a new command, and 2) it just feels slicker.

The idea is that this is an advanced feature, and would not be listed on the help page (`?`).  It would be described in the wiki.

### CODE REVIEW

**Comment by smblott-github** [comment]
@mrmr1993 (and @philc).  What do you think of this?  In particular, the use of flags is a big departure from the established Vimium way of things.

**Comment by mrmr1993** [comment]
I like it. Code LGTM.

**Comment by smblott-github** [comment]
This seems to give a very natural search interface.  Here's one configuration (which works for me)...

Custom search engines (a subset):

```
# Wikipedia.
w: http://en.wikipedia.org/w/index.php?title=Special:Search&search=%s Wikipedia

# Google.
g: https://www.google.ie/search?q=%s Google
l: https://www.google.ie/search?btnI&q=%s I'm feeling lucky...
```

Custom search-engine mappings:

```
# Google custom searches.
map ss Vomnibar.activate keyword=g
map sS Vomnibar.activateInNewTab keyword=g

# Wikipedia custom searches.
map sw Vomnibar.activate keyword=w
map sW Vomnibar.activateInNewTab keyword=w

# Google "feeling lucky" custom searches.
map sl Vomnibar.activate keyword=l
map sL Vomnibar.activateInNewTab keyword=l
```

**Comment by smblott-github** [comment]
Two things:
- I expect to merge this soon.  It's the way to go.
- There's a new wiki page describing vomnibar usage and tips [here](https://github.com/philc/vimium/wiki/Using-the-Vomnibar).

FYI ping @philc.

**Comment by mrmr1993** [comment]
@smblott-github Based on this, can we prioritise a review of the help dialog? This opens the door to it becoming either hugely bloated or gradually becoming disconnected from what we offer (in addition to visual mode, which it already ignores).

For me, #1280 proposes the best solution to the help dialog issue, but conversation there seems to have stopped.

**Comment by philc** [comment]
This looks okay to me and it's a cool idea. Before we share this with the
world, let's think about other use cases we may want to support and ensure
this syntax naturally extends to those use cases.

Another approach to parameterizing commands that I've seen is to use
something a little closer to actual javascript syntax, with positional
arguments, e.g.

`map sw Vomnibar.activate("w")`

Some possible future keybinding use cases to think through, off the top of
my head:

Mapping a key to:

* Go N pages back in history
* Close N tabs
* Open a bookmark with a given name, or a specific URL

I think this intersects with a proposal we've had on the issue tracker
awhile back for letting users define custom commands.

With this PR we certainly don't need to think through all of the
implications of doing that, or decide whether we want to, but it's worth
sanity checking whether this PR is a reasonable start down that path, or
whether it should wait until we've further baked our plans for/stance on
more sophisticated keymappings.

**Comment by smblott-github** [comment]
(Unnecessarily long post deleted, and replaced with...)

I'm confident we're not unnecessarily closing any doors here.

**Comment by smblott-github** [comment]
@philc.  The *options-like-Javascript-parameters* approach doesn't seem like the way to go.  With parameters, order matters.  So, if in the future we had multiple options, then the user would have to set the first even if they only cared about the second, and they'd have a to set a default value, and then we couldn't change the default value.  All of which is unnecessarily complicated.

The approach here seems both easy to understand and extensible.  For example, we could extend it to include on/off flags (`something`, `nosomething`), options whose values contain spaces (`key="some value"`), arbitrary JSON (`key="[1,2,3]"`).  I'm not proposing doing any of that now, just noting that those doors are not closed. (We'd possibly have to write a parser for the more complicated cases.)

Important point.  Keep the simple cases simple.  And the approach here achieves that.

@mrmr1993...

> or gradually becoming disconnected from what we offer

My sense is to keep the help page simple for noobs, and put the advanced stuff on the wiki.  Although, separately, we could do a better job of keeping the wiki up to date.

Will merge this.  Having key bindings for custom search engines is a nice feature.  I'll also make sure this is well described in the wiki.

**Comment by smblott-github** [comment]
It turns out there's a problem with this.  It mucks up the layout of the help page...

snapshot

**Pull request merged**
