### PR TITLE
Link hints context-menu mode

### LINKED ISSUE #1312: Proposal: implement a Vimium-specific right-click menu for links
Hey everyone, what do you think about a Vimium-specific right-click UI as a means to gracefully scale the number of commands that one may want to perform on a link?

You would "right click" on a link using link hints, and then get a popup, where each action has a reasonable hotkey:

image

Comments

* We can handle lots of commands this way without introducing new top-level commands.
* Since you don't need to bind any of these sub-commands to specific keys, it means you'll have to remember fewer keybindings to be able to use these commands. This is a nice property since most of these would see relatively rare usage compared to other top level commands.
* This naturally mirrors the interaction model Chrome uses for this use case.
* The UI elements are based on Chrome's right click menu (at least what they look like in OSX). The link which is being operated on is highlighted as it is when you right click using the mouse.
* The specific use case of hovering probably requires more thought, since you'll want to be able to unhover as well. Perhaps this is how you hover, and then hitting esc at any time unhovers.

Related issues: #484 and likely many others.

### PR DESCRIPTION
**Pull request by smblott-github**
This implements @philc's idea from #1312, a link-hints mode which activates a menu.

We get a lot of a requests for new link-hints modes.  Each new mode requires a new command, and we arguably already have too many commands.  The idea here is that - for less common modes - we can add a new menu operation instead.

Details:
- Default binding: `gm`.
- This PR also adds a hover option (borrowed from @mrmr1993's #1032).
- And it adds a "yank-link-text" option (borrowed from @svgsponer's #1947).

Currently, it looks like this...

snapshot

To do:
- internationalisation?
- with queue

Fixes #1312.
Replaces #1032.
Replaces #1947.

### CODE REVIEW

**Comment by mrmr1993** [comment]
Nice work at implementing #1312. I'm quite disappointed though; I was expecting to like this much more. My initial thoughts:
* the order in which you make decisions with the menu &mdash; choosing the object before the action &mdash; feels very un-vim-y. It might just be me, but I feel as though I've lost power, asking Vimium what I *can* do with the link rather than telling it what *to* do.
* this 'solves' the 'problem' of having too many commands by
  - still adding them
  - giving them restricted bindings
  - hiding them and their descriptions away in a menu (that itself is hard to find in the help dialog).

After using this, I feel like we're trying to solve a documentation problem with program design. Sorry Steve, but I think we should bin this and sort out #1269 (command zoo) another way. I'm going to look at implementing #1280 again over the next 2-3 days.

**Comment by nfischer** [comment]
I'm ok with having something like "open in incognito" in a sort of right-click menu (as long as I can "right click" with link hints of course). These all seem obscure enough that it's ok to put them in a menu (as long as f and F still work as before). Just my 2 cents

**Comment by philc** [comment]
I have some comments, I'll chime in later.

**Comment by smblott-github** [comment]
> These all seem obscure enough that it's ok to put them in a menu

Yes, @nfischer.  This is a win for me too.  I use the lesser known link-hint modes so infrequently that I can never remember the binding, so it's quicker to reach for the mouse.

**Comment by philc** [comment]
* "Right clicking" is an important action in web browsing that everyone is already familiar with. When I think
  about download a link's content or copying its URL, the first thing I think about is right clicking on that
  link.
* The actions taken via the right click menu are rare enough that the keybindings won't be remembered by most
  people. I still use the mouse to download links even though we have a command for it (which feels like a
  fail). Presenting a menu will really help with this problem. Now you need to remember just one command
  rather than many.
* You can still efficiently invoke these commands if you've memorized the keybinding: f; type the hint;
  immediately type the action you want.
* While you could argue that most Vim commands don't ask you to select the object before specifying the
  command, that is the way visual mode interactions work. @mrmr1993, regarding your feeling of "loss of
  power", one way to think of this is that it's progressive disclosure of (somewhat rare) actions which are
  available on a link. Kind of like listing a directory before selecting the file to open. Necessary and
  helpful.

Let's debate whether we make available standalone commands for some of these actions like `copy link address`. What do you guys think? I can see the value in keeping separate bindable commands if you perform one of the right click actions very often, like downloading files.

Some feedback on the UI:

* I think the aesthetics of this dialog should reflect the mock from #1312. In particular, the hints should be
higher contrast to the captions, e.g. bold and bluish, similar to the help dialog.
* The hrs should have less contrast
* Use the same margin above and below the menu's content as you use for the sides.
* (I'm happy to tweak the styles once merged)
* I haven't played with this yet, but just to preemptively QA this, the menu should be positioned fully
  on-screen even if the link is near the bottom of the view port

**Comment by nfischer** [comment]
> Let's debate whether we make available standalone commands for some of these actions like copy link address.

I think each of those commands are obscure enough that, if they don't already have a binding, then a three-key binding (`gmt`, `gmd`, etc.) is probably fast enough. Anyone who has memorized the binding probably won't mind seeing the menu pop up on screen for the split second between pressing `m` and pressing `d`. If it turns out to be a major concern, you could expose the command (i.e. download link) without providing a default binding, letting the user decide without cluttering the docs by default.

I think the binding would be better if it was related to `f`. I'm guessing `gm` stands for something like "go to menu," which is intuitive enough, but I think it'd be better to press something like modifier-`f` and type in a link hint. I just can't think which modifier is left remaining.

**Comment by mrmr1993** [comment]
I disagree on a fundamental level @philc. Screen real estate already has semantic meaning, and a context menu is a tool to repurpose it to provide more options beyond the descriptive power of saying "that, there". You need a context menu to change actions into visual action 'objects', otherwise they wouldn't be accessible from the mouse.

The keyboard is (for us at least) fundamentally different: the meaning of the keys change based on some not-necessarily-visual state. Briefly,
* the power in *expressing* any of these actions is unchanged by using a context menu; hide the menu and the keybindings are as accessible or inaccessible as any other.
* the menu represents a documentation hack, insofar as it
  - hides some commands separately from the others, so that frontline documentation is less dense
  - adds no extra contextual or other information to the commands by putting them there
  - preventd the documentation from being accessible at the same point as all other command documentation.

To address your comments,

> * "Right clicking" is an important action in web browsing that everyone is already familiar with. When I think about downloading a link's content or copying its URL, the first thing that comes to mind is right clicking on that link.

To have a dedicated visual button is a waste of space: visually a context menu is better. But for Vimium, it saves no space, apart from in documentation.

> * The actions taken via the right click menu are rare enough that the keybindings won't be remembered by most people. I still use the mouse to download links even though we have a command for it (which feels like a fail). Presenting a menu will really help with this problem. Now you need to remember just one command rather than many.

This is also a documentation issue. Can you remember the command to scroll all the way to the right/left? I can't. But I might still need it on occasion.

Actually, it takes long enough to identify that from cold in the help dialog that a command search would be a large improvement. Hell, enter from that search could launch the command, so a moment's forgetfulness barely slows you at all. I can't see that hiding it in a special scroll context menu &mdash; that I also need to remember the command for &mdash; is going to help anything except the number of commands the help dialog opens with.

> * You can still efficiently invoke these commands if you've memorized the keybinding: gm; type the hint; immediately type the action you want.

There's two context changes here: command, object, command. Which seems like a waste of mental effort when it could be just command, object. Otherwise, I agree that these are just mappings in disguise.

> * While you could argue that most Vim commands don't ask you to select the object before specifying the command, that is the way visual mode interactions work.

Agreed. Visual mode is better for some harder-to-describe (in Vim movement terms) cases. Are any of these actions hard to describe in simple, atomic terms?

> @mrmr1993, regarding your feeling of "loss of power", one way to think of this is that it's progressive disclosure of (somewhat rare) actions which are available on a link. Kind of like listing a directory before selecting the file to open. Necessary and helpful.

I agree, progressive disclosure (or interactive documentation, as you might call it) is necessary and helpful. But this is relegation with interactive documentation, and I'm not sure that we need to relegate these commands, nor that the interactive documentation to be so restrictive and restricted.

Please lets not fuck up commands over a documentation issue.

**Comment by nfischer** [comment]
> Actually, it takes long enough to identify that from cold in the help dialog that a command search would be a large improvement. Hell, enter from that search could launch the command, so a moment's forgetfulness barely slows you at all.

^ That's actually a pretty neat idea. It might be worth opening that as an additional PR

**Comment by mrmr1993** [comment]
> It might be worth opening that as an additional PR

Thanks @nfischer. I want to see if @smblott-github and @philc  approve first, otherwise I'll have to fully commit to forking to make that PR worthwhile.

**Comment by nfischer** [comment]
@mrmr1993 I went ahead and wrote the searchable help menu up as a separate issue, since I don't think it necessarily solves the same problem, but I think it's worth consideration regardless of whether this gets merged or not.

**Comment by smblott-github** [comment]
Update:

- Better styling.
- Match layout of #1312.
- Menu should (?) now always be in viewport (although the position calculation could be more subtle).

snapshot

To do:

- There are still some styling issues on some pages.  (E.g. For some reason, the separators don't show on github pages.)  My CSS foo is weak.

**Comment by philc** [comment]
I'm going to solicit some more external input on this feature early this week.

**Comment by smblott-github** [comment]
Update...

I have used this link-hints menu precisely 0 times in anger.  This feature may not be as useful as first appeared.

**Comment by smblott-github** [comment]
Unless a champion emerges for this I propose to close it soon on the basis that it's not as useful as we thought.

(@mrmr1993... One thing that I like about this is the behaviour of "hover", where `Escape` unhovers.  That might be worth remembering.)

**Comment by nfischer** [comment]
I haven't tried this out yet (but I could over the next week). To me it would be useful if for no other reason than hover and unhover. One request I have though would be some sort of "click and immediately unhover" option. This makes sense when clicking the "make fullscreen" button for youtube videos, for example. It seems like this could often be the default behavior (although I suppose sometimes a "click and continue to hover" option is preferable).

**Comment by smblott-github** [comment]
Closing.
@mrmr1993 is strongly opposed to this (see above).  I'm mildly on the *no* side (because it's not as useful in practice as anticipated).

We can reopen this if a champion emerges.

**Comment by dragon788** [comment]
I'd still love to see something like this, if only to open links into another instance of Chrome logged in as a different user. On my work laptop this has become something of a daily occurrence where I am in my "work window" chugging along and then I see something I'd like to read later, I then right click and open it into my personal account's open session so that my Chrome tabs/history sync and I can read the page later. Using Chrome native features like this and not having to do a bunch of extra extension syncing (Pocket/Pushbullet/XMarks/etc) would be awesome. Maybe I just need to examine the source and see if there is a command already defined for this, though I'm using currently 3 different users in 3 different Chrome sessions, so it would have to have a way to present an option to select the user.

**Comment by Anak2016** [comment]
I agree that right click on a link feature is not as useful as it seem. Though, I feel the need to point out that right "clicking on the page" features would be extremely helpful when using along with other plugins. 
As of now, I have the following option when right clicking on a page. 
1. rename tab. really useful when doing tab search
2. highligther. This is really really useful when reading on a random page that you frequently visit.
3. Web Clipper. such as evernote. it is extremely useful in my case when i am doing research because I organized my notes within evernote.
4. using it with "copy page url" plugin. it allows you to copy url in various way. copy url and text, or copy text and embed url in it. imagine using it with EVernote mention above. This is a killer in my book. 

This is just plugins that i have. but i can imagine that It will be really useful in some other cases as well.

**Comment by mcp292** [comment]
The only reason I want right click is to copy ~~text~~ emails. For example, an email hyperlink gives the option to copy the email on the context menu. That is pretty much my main use case as it's hard to argue for copying text, because there's no way to highlight with just the keyboard and vimium.

**Comment by espoelstra** [comment]
> The only reason I want right click is to copy ~~text~~ emails. For example, an email hyperlink gives the option to copy the email on the context menu. That is pretty much my main use case as it's hard to argue for copying text, because there's no way to highlight with just the keyboard and vimium. 

Have you met visual or caret mode? You can totally highlight text using just the keyboard using the normal vim shortcuts to switch which direction to expand your selection.

**Comment by gdh1995** [comment]
@mcp292 Maybe the Vimium command named `LinkHints.activateModeToCopyLinkUrl` can help.

**Comment by mcp292** [comment]
> Have you met visual or caret mode? You can totally highlight text using just the keyboard using the normal vim shortcuts to switch which direction to expand your selection.

No actually! Will have to check it out!

**Comment by mcp292** [comment]
@gdh1995 I don't know if that would work since I don't want to copy the `mailto:` portion of the url.

**Comment by gdh1995** [comment]
Vimium will auto trim a `mailto:` prefix.

**Comment by mcp292** [comment]
@gdh1995 Ah shit! Nice!

**Comment by mcp292** [comment]
@gdh1995 It doesn't auto-trim `http://`. Try the `yf` on the email links on this site:
https://sendcutsend.com/design-partners/

**Pull request closed without merging**
