### PR TITLE
show favIcons for browser tabs on Vomnibar

### PR DESCRIPTION
**Pull request by gdh1995**
This make Vomnibar show favicons of current browser tabs. Implements #2847 .

### CODE REVIEW

**Comment by smblott-github** [comment]
This looks quite nice, actually.  I was a little surprised...

image

However, we need a decision on #2656.  If we go with that proposal, then we'd need to make sure the two look ok together.

**Comment by seniorivn** [comment]
for urls in #2656 we can use google favicon resolver, so there will be consistent view(with a fallback image for unresolved favicons)
http://codingclues.eu/2009/retrieve-the-favicon-for-any-url-thanks-to-google/

**Comment by mmikeww** [comment]
bump

**Comment by philc** [comment]
Looks great. Merged in cea42f3bd370d44531f0d76b7923f5bf7e67c19b. Thanks!

**Pull request closed without merging**
