### PR TITLE
Ignore keyboard layout

### PR DESCRIPTION
**Pull request by SHTrassEr**
I use two keyboards layouts: English and Russian. In English layout all fine. But when i switch to Russian keyboard layout i can not longer scroll page or switch between tabs. The most interesting thing that I can still open links.

Of course, It is possible to add key mapping for Russian caracters, but it is inconvenient.

These changes add ignoring keyboard layouts.

### CODE REVIEW

**Comment by Smeagol07** [comment]
As Vim does not care bout the layouts as this extension shouldn't. It surely could be added as an option but not as default one, really.

**Comment by slavaGanzin** [comment]
@Smeagol07 In vim you can easily achieve this with:
```
cnoreabbrev RU set keymap=russian-jcukenwin
cnoreabbrev ENG set keymap=
```

And it was a bit, you know, frustrating to find that. 

Also constant rewriting language maps in vimium isn't ok too. But I think your polish friends would appreciate(as I appreciate work of @pletinsky and @tmp6154) if you spend your time adding keymap here: https://github.com/philc/vimium/wiki/Key-Mappings

**Comment by Smeagol07** [comment]
@slavaGanzin Polish keyboard layout is the same as US one, nothing to change.

**Comment by smblott-github** [comment]
Closing.

Out of date.

**Comment by mortdeus** [comment]
I have no idea why this was important to me, but I just remember it was. lol

**Pull request closed without merging**
