### PR TITLE
Use document.scrollingElement for scrolling

### PR DESCRIPTION
**Pull request by dpogue**
This fixes Vimium with the 'Experimental Web Platform Features' flag enabled, and ensures compatibility across quirks mode scrolling (via `document.body`) and standards-compliant scrolling (via `document.documentElement`).

Includes a polyfill for `document.scrollingElement` that returns `document.body`.

### CODE REVIEW

**Comment by smblott-github** [comment]
Thanks, @dpogue.  Could you flesh out your explanation a bit please; e.g. why does the status quo break? and why does this fix that?

(FYI: Vimium development is going into summer recess soon; I won't get time to think about this properly until August.)

**Comment by leoj3n** [comment]
@smblott-github One more day! :D

I'm also curious about an explanation @dpogue; What exactly breaks or what exactly changes about scrolling with the experimental flag enabled?

**Comment by dpogue** [comment]
Historically, in quirks mode, browsers applied scrolling the `body` element. In standards mode, scrolling is applied to the document element (`html` in most cases). However, Webkit (and thus Blink) applied scrolling to `body` regardless of the mode.

This led frameworks trying to measure scrolling to resort to trying to handle all cases:
```javascript
scrollTop = (document.documentElement.scrollTop + document.body.scrollTop);
```

`document.scrollingElement` was added to the CSSOM spec to provide a consistent way of accessing scroll position, regardless of mode.
  
  
The reason we need to use it here is because Chrome has started following the spec and applying scrolling to the document rather than to the body, when the "Experimental Web Platform Features" flag is enabled.
  

This PR provides a safe (for Chrome) polyfill, in that it defines `document.scrollingElement` to be `document.body` if it does not already exist. Thus existing behaviour is preserved for people running without the experimental flag.

**Comment by leoj3n** [comment]
Ah, so this _is_ related to #962 and #1138.

**Comment by smblott-github** [comment]
Thanks for the explanation, @dpogue.

Something doesn't seem to be right yet.  On [this simple page](https://www.x.org/releases/X11R7.7/doc/libX11/libX11/libX11.html), I seem to have to click the page to get scrolling to work.  Any ideas, @dpogue?

**Comment by smblott-github** [comment]
Ping @dpogue... (see my comment above).

**Comment by gdh1995** [comment]
I approve this idea, because Chrome has "invented" a flag `#enable-experimental-web-platform-features` to allow `document.scrollingElement` to be `<html>` on some pages.

In my recent tests with this flag enabled, some pages did scroll `<html>`, although the other pages scrolled `<body>` as before. I haven't found any rule to predict which one they choose, and Vimium's options page scrolled `<body>`.

BTW, on my Chrome 53 x64 stable with the flag disabled, Vimium `master` can scroll [The Xlib page above](https://www.x.org/releases/X11R7.7/doc/libX11/libX11/libX11.html) directly (no click needed). But after applying this PR, a click becomes needed.

**Comment by gdh1995** [comment]
The bug in this PR is:
* if `document.scrollingElement` is not defined, it setups it using `document.body` on `scroller.coffee` is being executed, but at that time the page is beginning to load and `document.body` is always `null`.

A fix may be:
* define `.scrollingElement` using a `getter` function which always return `.body`.

**Comment by dpogue** [comment]
I've fixed the issues with scrolling not working immediately on page load. It was due to CoffeeScript's `in` operator being different than JavaScript's `in` :(

**Comment by dpogue** [comment]
I wasn't able to reproduce that case with any of Chrome stable, dev, or canary, with the experimental-web-platform-features flag both on and off; but I've updated the PR to use a getter just to be safe.

**Comment by gdh1995** [comment]
(I don't know why, but) Not all pages use `document.documentElement` as their scrolling root if `#experimental-web-platform-features` is enabled, and in my tests, Vimium's options page is just such a page which still insists using `document.body`.

It seems that a valid `<!DOCTYPE >` is needed to make `<html>` the scrolling root. You may try https://jsfiddle.net/86bpy7pw/.

**Comment by smblott-github** [comment]
Thanks, @dpogue.  I'm going to merge this, but like this: 07bc4fbe820ff17b5a6b559a2ebcceb7d52700a2.

**Pull request merged**
