### PR TITLE
Populates vomnibar input with url ( Issue #2464)

### PR DESCRIPTION
**Pull request by Gu1nness**
When <Tab> is pressed, if the suggestion is a bookmark or history,
populates the input with the corresponding url.

Refers and solve  https://github.com/philc/vimium/issues/2464

### CODE REVIEW

**Comment by smblott-github** [comment]
Thanks, @Gu1nness.

This is quite a big change to the usability of the Vomnibar.  There are use cases where this is the right thing to do, and probably others where it is not.

A (less discover-able) alternative might be to use `<Control-Enter>` to copy the currently-selected URL to the input.

Bottom line... I'm not sure.

<hr>

Separately...

1. If the URL inserted into the input is too long for the input, then we probably should put the focus at the end.
2. What does it mean to do this in tabs mode (`T`)?
3. There's something very broken in tabs mode and in bookmarks mode (`b`).  Selecting an entry and editing the input, you'll see.

**Comment by Gu1nness** [comment]
Indeed, I had missed these points (actually I didn't even know that this exists).
I'll look into it so this can be patched.
I agree for the `<Control-Enter>` this way it won't break the workflow the users.

**Comment by Gu1nness** [comment]
Hi @smblott-github ,
I eventually pushed a new version, with <Ctrl-Enter> .

**Comment by Gu1nness** [comment]
I have corrected the small typo that I had mistakenly inserted.

**Comment by philc** [comment]
I wasn't able to merge this PR directly due to conflicts, but pushed your change in 2268e498637bc3190070e3d32146f981a33be726. I hadn't realized I've been missing this all these years. Thank you @Gu1nness !

**Comment by philc** [comment]
I wish this was easier to discover. It would be cool to somehow have an opt-in cheat sheet built into Vomnibar, in the same spirit as typing "?" in Vimium. For now, I've documented this feature on [this wiki page](https://github.com/philc/vimium/wiki/Tips-and-Tricks).

**Pull request closed without merging**
