### PR TITLE
[Enhanced] Execute "javascript:" URLs by injecting them into the page itself.

### LINKED ISSUE #3178: Javascript bookmarks not working anymore
My javascript bookmark use to work on Chrome 69, but it doesn't on version 71.0.3578.30.

Its content is:
`javascript:(function()%7B(function () %7Bvar i%2C elements %3D document.querySelectorAll('body *')%3Bfor (i %3D 0%3B i < elements.length%3B i%2B%2B) %7Bif (getComputedStyle(elements%5Bi%5D).position %3D%3D%3D 'fixed'||getComputedStyle(elements%5Bi%5D).position %3D%3D%3D 'sticky') %7Belements%5Bi%5D.parentNode.removeChild(elements%5Bi%5D)%3B%7D%7D%7D)()%7D)()`

https://github.com/philc/vimium/pull/3167 might solve this.

### PR DESCRIPTION
**Pull request by gdh1995**
This is an enhanced version of #3211, and adds `try decodeURI` to `javascript` URLs.

Replaces and fixes #3211.
Replaces and fixes #3209.
Fixes #3178.
Fixes #3246 .

### CODE REVIEW

**Comment by philc** [comment]
Great work @gdh1995. Thank you!

**Comment by patkujawa-wf** [comment]
Thanks guys!

**Comment by patkujawa-wf** [comment]
@philc I'm not seeing this release in Chrome (it thinks 1.64.6 is the latest).

**Comment by patkujawa-wf** [comment]
I see it now - thanks!

**Comment by andreehai1011** [comment]
Thanks for the effort, now my engine "Search in current site" is working
eg: cs: javascript:location='http://www.google.com/search?num=100&q=site:'%20+%20escape(location.hostname)%20+%20'%20%S'%20;%20void%200 Current site

**Pull request merged**
