### PR TITLE
CSS overrides for Vomnibar + optional overlay behind it

### PR DESCRIPTION
**Pull request by bezhermoso**
Nothing particularly game-changing -- just added a white translucent overlay behind the Vomnibar to increase visibility. Also softened the shadow up a bit (mimicks OS X Spotlight bar closely).

vimium omnibar focus

I understand that this change is purely aesthetic. Just putting it in here in case people are interested.

### CODE REVIEW

**Comment by gdh1995** [comment]
I'm sorry but, I often use Vomnibar to query a English word on the page, and this PR does hide the background text.

**Comment by bezhermoso** [comment]
Thanks for the feedback @gdh1995 

So I changed how I go about accomplishing this. Instead of modifying the existing CSS styles for the Vomnibar, I added a few settings under Advanced Options:

* `userDefinedVomnibarCss` - This will be loaded into `vomnibar.html` when it is first built. If people wish to change how the Vomnibar looks, they can override the CSS here.
* `overlayBehindVomnibar` - A checkbox that will toggle the overlay behind the Vomnibar. Defaults to `false`.
* `userDefinedVomnibarOverlayCss` - If people want to override the CSS style of the overlay, they can do it here.

**Comment by smblott-github** [comment]
The added functionality here doesn't seem to warrant the extra noise on the options page.

Shout if you'd like to argue otherwise.

**Comment by bezhermoso** [comment]
@smblott-github Even considering that its under advanced category?

We have `CSS for link hints` under advanced options, and this would fall under the same category. It is exactly the same functionality, just styling different aspects of Vimium.

**Comment by smblott-github** [comment]
@bezhermoso.  There's actually a desire knocking around with some to get rid of the `CSS for link hints` option.  If it weren't there, it wouldn't be added.  And if weren't for the inconvenience to some passionate existing users, it probably would go.

**Comment by bezhermoso** [comment]
@smblott-github 

Are you referring to this? https://github.com/philc/vimium/issues/636

It is not clear to me if the reason for removing the feature is because of:

A. the chance that user-defined overrides _may_ break because Vimium isn't promising non-breaking changes to the markup to UI elements, or
B. something more technical?

**Pull request closed without merging**
